### ISSUE TITLE
ArrayIndexOutOfBoundsException: 0 in training

### ISSUE THREAD

**Issue by vallettea** [deeplearning4j/dl4j-spark-ml#6]
Does somebody encountered such an exception at runtime during the training ?

```
[WARN] [TaskSetManager] Lost task 3.0 in stage 5.0 (TID 23, localhost): java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.java:970)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:3920)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1115)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:3891)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:122)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:112)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:89)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:81)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

my NN being defined by:

```
        val numInputs = 10
        val outputNum = data.nbClasses
        val iterations = 10
        val seed = 6L

        println("Build model....")

        val conf = new NeuralNetConfiguration.Builder()
          .seed(seed)
          .iterations(iterations)
          .learningRate(1e-3)
          .l1(0.3).regularization(true).l2(1e-3)
          .constrainGradientToUnitNorm(true)
          .list(2)
          .layer(0, new DenseLayer.Builder().nIn(numInputs).nOut(500)
                  .activation("relu")
                  .weightInit(WeightInit.XAVIER)
                  .build())
          .layer(1, new OutputLayer.Builder(LossFunction.MCXENT)
                  .weightInit(WeightInit.XAVIER)
                  .activation("softmax")
                  .nIn(500).nOut(outputNum).build())
          .backprop(true).pretrain(false)
          .build()
```

**Comment by EronWright** [comment]
From the stack trace, I suspect that the dataframe has an empty partition.     Please elaborate on how your dataframe was constructed, thanks.

**Comment by vallettea** [comment]
you where right I had some empty partitions (though I don't understand why). I solved the problem with:

```
        val learningSet = extract
            .map(entry => {
                LabeledPoint(entry.origin, Vectors.dense(entry.destination))
            })
            .mapPartitions(batch => {
                println(s"batch size: ${batch.size}.")
                batch
            })
            .repartition(8)
            .toDF.cache
```
